language: scala
git:
  depth: 9999
scala:
- 2.12.7
jdk:
- oraclejdk8
install:
- pip install --user codecov
script:
- sbt coverage "tests/test" coverageReport
- codecov
cache:
  directories:
  - "$HOME/.sbt/1.0/dependency"
  - "$HOME/.sbt/boot/scala*"
  - "$HOME/.sbt/launchers"
  - "$HOME/.ivy2/cache"
before_cache:
- du -h -d 1 $HOME/.ivy2/cache
- du -h -d 2 $HOME/.sbt/
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
before_install:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then openssl aes-256-cbc -K $encrypted_f5dd5ea7c332_key
  -iv $encrypted_f5dd5ea7c332_iv -in travis/secrets.tar.enc -out travis/secrets.tar
  -d; tar xv -C travis -f travis/secrets.tar; fi
env:
  global:
    secure: mU1Rax5OaQHBt1otdKZIMJZjowlhq3QdYmaMfqtD/frx40skbADNR3CKupu1G8FMMybyb+K5Zlayr6rA0QPPzpFz9PbTjSf1n61sE/TaXDpD2zHdrih3p2MPijYHnP5ssjlG5+yJei9sN4Qu2PKXRetGeJi6j6JkyUClmTgcnkAUIq52S6DAsBP4AZeyMou8WGlxu7tOcMMHCVd4vPrXGHNsDMF23A9+6xl1YpWbLUM0mQ2KI6SYjPt5r2sfvU5PW/VGxrR2zhseL8tIhs1CP9ihU4tLzre7kmI7DnXbsKxrUOu/RVVfzptnq294FxIEODNDi6o0V74bAVpJWVexJfpcm7Dsk/V7XKcegLXJywjmosgW4sfkXuLx7G9LRixCZMualXxEdd/o2klVBD8vLKU2AA/C2QPqrJUXvUMskf+r3f72MCmq1J/leucCWSE+r4otlogvVhSsXagP7lyTAzKxN0odQD3+Bp0tpWl4yKhLJ/urfy4U9k4hJ4T7lVcpc8iuDiVN+OTx1D9+s7vjkuBwIODJ3HqH6rhDsjcGYBRQ22VQbt9PAH1+8wVZYugq52CKimBT/yhRAj1K/EO1NTkw+JTtPhGQL1jKE3AAYogkIgG+bw5+ILHJu3aYQ0m37eU7cogZb7utzbY0Af4OjwCSlQ8FmruheVmdhPvFZ+w=
after_success:
- if [ $TRAVIS_PULL_REQUEST = 'false' ]; then sbt releaseEarly; fi
dd:
  secure: Ralqvbga9O0jiHDApxzzg5Jf8vkVs9FMDZApkwxdneopDHNTv6SaJqDlWQIh2ypE8643yVBxuZlb/24BJPndZfa5MStbOyBUdo+6tO8N5+a+9YX3rbeJwPdCdtc6f9vyodyWEKCYKDB2YBfoLM78OajpQQQuXOJRsDfSVZc8Pvt1x0YfZyN87fPjUqUboYua/BpzfW0LH/MvENvRwLnRG/rrWTF/VL4oozOo3E8JG5s25JqOBLL/JJneRN9Wgk7bOI/5Pui4KEnWaVxkM1iUvcj/b1JhxtlvPyP026wOqbZbL16oArSq9hjPNMRumG+E1IA/ix4vY3+iYjEDkNJ7Sk7Yv955QhU1nIlhoLZ0D+AaUi8cfRPpuHQw3uR9AaV/hSGwfaTblmsPjYW4EZuTcipSlf3BBama/97UwP70Wqupo4eu2RuN3rb3Gz8A5Lx3GkMYMpSDyIHw7ctqxljN/HhgoAugotLGyUimeTVi1t7GmHo2DgV9Kc9kvxaljxYcCm387Yo9v58kqRnKvz2IrClgWc8rOGShno9VQ98nllF82e3+q+ZaDt0oTHqCCB7NUWWQfQX05J70GVtjA724CJUHwvwNyQSd28qfH7ntV03fQzxt4/Qx2wX/SpB0c9jKbCpZlgbUrW0xDIqhJfZek0PYFb7JTlulcy3sftRVCAU=
