name: itinere
baseurl: /itinere
description: Describe HTTP REST/JSON endpoints
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.1+10-777a55a7
org: net.vectos
markdown: kramdown
