name: itinere
baseurl: /itinere
description: Describe HTTP REST/JSON endpoints
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.2+6-541188bc
org: net.vectos
markdown: kramdown
