name: itinere
baseurl: /itinere
description: Describe HTTP REST/JSON endpoints
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.2.2+16-52c822b3
org: net.vectos
markdown: kramdown
